language: minimal

stages:
- name: image
  if: branch = master AND type != pull_request
- name: new-git-release
  if: tag is present

services:
  - docker

before_script:
  - export DOCKER_REGISTRY=${DOCKER_REGISTRY:-quay.io}
  - export IMAGE_NAME=${IMAGE_NAME:-/st4sd/official-base/st4sd-datastore-mongodb}
  - export IMAGE_BASE_URL="${DOCKER_REGISTRY}${IMAGE_NAME}"

jobs:
  include:
    - stage: image
      os: linux
      script:
        - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN $DOCKER_REGISTRY
        - docker build -f Dockerfile -t ${IMAGE_BASE_URL}:latest .
        - docker push ${IMAGE_BASE_URL}:latest

    - stage: new-git-release
      os: linux
      services: docker
      script:
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - docker login -u $DOCKER_USERNAME -p $DOCKER_TOKEN $DOCKER_REGISTRY
        - docker manifest create ${IMAGE_BASE_URL}:${TRAVIS_TAG} ${IMAGE_BASE_URL}:latest
        - docker manifest push ${IMAGE_BASE_URL}:${TRAVIS_TAG}
        - docker manifest create ${IMAGE_BASE_URL}:release-candidate ${IMAGE_BASE_URL}:latest
        - docker manifest push ${IMAGE_BASE_URL}:release-candidate
